### ISSUE TITLE
Executive Logic: Overarching Logic

### ISSUE THREAD

**Issue by Wilson-Orlando** [poszy/def_spinit_project#9]
Currently, executive logic has several small helper functions, but nothing to handle stepping through the other modules. For example, once a player's turn starts, we need a sort of "main" method that will call Wheel to get their spin result, then give the info to UserInterface to display, then call Board to get their Jeopardy question, and so on.

This issue covers the definition and implementation of one or more additional methods in ExecutiveLogic that will cover the overarching game logic described above. Once completed:
- The system should be able to step through the flow of a game from "game start" to "game end". For example, "Game start" -> "player turn" -> "spin wheel" -> "board question", and so on.

See use cases 3 & 4 in section 3.1 of the software req specification for more info on game logic

**Comment by Wilson-Orlando** [comment]
From our 7/21 discussion, here's how this should work:
- Server calls runGame() method from ExecutiveLogic
- ExecutiveLogic.runGame() contains all the game logic, calls other module's interfaces, etc.
- runGame() returns back to server when game is complete

Also remove other module initializations (like Board, Wheel, etc) from server.py

**Comment by Wilson-Orlando** [comment]
Note to self: get started implementing the 5 executive logic methods

**Comment by robyntorregrosa** [comment]
Update: We discussed this in the discord, the server is just going to be responsible to sending/receiving messages from the client. The ExecLogic will instantiate the server.

**Comment by robyntorregrosa** [comment]
Question, when server receives message from the client (e.g. "spin"), how does the server tell the ExecLogic to then tell the Wheel?

**Comment by Wilson-Orlando** [comment]
> Question, when server receives message from the client (e.g. "spin"), how does the server tell the ExecLogic to then tell the Wheel?

Reposting our discussion from the discord: ExecLogic now passes a reference of itself to GameServer when GameServer is instantiated.
